### PR TITLE
Change URLs to HTTPS

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
let's try this. :)

**Comment by ekohl** [comment]
Do you know how this is rolled out?

**Comment by mmoll** [comment]
nope, I hope automatically somehow...

**Comment by GregSutcliffe** [comment]
Just going through old notifications, missed this. I guess you figured it out, but yes it's automatic - there's a Jenkins CI job to deploy the website.

**Comment by ekohl** [comment]
@GregSutcliffe this is the prprocessor and that's manual deployment :)

**Comment by GregSutcliffe** [comment]
/me has read too many notifications this morning.

**Pull request merged**
