### PR TITLE
Collect issue numbers from all commits in a PR

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by ekohl** [comment]
Won't this change the behavior so that any commit should have an issue number rather than all commits?

**Comment by tbrisker** [comment]
@ekohl i don't think so, `check_commits_style` checks every commit for the right format.

**Comment by tbrisker** [comment]
ping @ekohl ?

**Comment by tbrisker** [comment]
this has been implemented already in the new bot, closing.

**Pull request closed without merging**
