### PR TITLE
Fixes #107 - check for uninitialized commit authorship

### LINKED ISSUE #107: check for 'root' or 'vagrant' in email address
It's easy to mistakenly create a commit as 'root' or 'vagrant' user, and difficult to spot this error when doing PR review. It would be good if the prprocessor checked for this.

I don't have a dev environment for prprocessor, but I believe something like this untested patch should do it:

```diff
diff --git a/github/pull_request.rb b/github/pull_request.rb
index 980938a..31c221f 100644
--- a/github/pull_request.rb
+++ b/github/pull_request.rb
@@ -98,6 +98,10 @@ class PullRequest
         warnings += "  * #{commit.sha} must be in the format ```fixes #redmine_number - brief description```\n"
         short_warnings[commit.sha] << 'issue number format'
       end
+      if commit.commit.committer.email =~ /\A(vagrant@|root@)/
+        warnings += "  * #{commit.sha} must not be authored by vagrant or root user\n"
+        short_warnings[commit.sha] << 'vagrant or root in commit author email'
+      end
       if commit.commit.message.lines.first.chomp.size > 65
         warnings += "  * length of the first commit message line for #{commit.sha} exceeds 65 characters\n"
         short_warnings[commit.sha] << 'summary line length exceeded'
```

### PR DESCRIPTION
**Pull request by beav**

### CODE REVIEW

**Comment by beav** [comment]
@ekohl this is the patch for the issue. It ran fine with ruby -c and I tested the regex in IRB. Once it's updated, I can run [test prprocessor] on a commit that should trigger the failure

**Comment by ekohl** [comment]
> Once it's updated, I can run [test prprocessor] on a PR that should trigger the failure

AFAIK there is no way to actually trigger it like that - only opening a new PR / pushing an incorrect author to an existing PR. Still, should be ok. I'll have a look on Monday.

**Comment by ekohl** [comment]
Merging and monitoring.

**Comment by ekohl** [comment]
Rolled out and tested in https://github.com/theforeman/puppet-katello_devel/pull/161.

It's important to note this is only applied on repos where `redmine_required` is true. Another thing to note is that it only checks the committer, not the author. Probably good enough in this case but the `redmine_required` probably means we miss some things.

**Comment by beav** [comment]
@ekohl I goofed and meant author instead of committer, I didn't realize they were two different fields until just now. I tested by creating a commit with author of "vagrant@example.test" in the katello repo that didn't get picked up.

I'll put in a new PR to fix this, thanks for checking this.

**Pull request merged**
