### PR TITLE
[WIP] Set the release field of an issue when merging

### PR DESCRIPTION
**Pull request by ekohl**
This is untested and I'm not sure how we can test this other than using it in production given the current infra we have.

Includes https://github.com/theforeman/prprocessor/pull/105

cc @mhulan

### CODE REVIEW

**Comment by ehelms** [comment]
If Foreman core tries to do core triage (which there is a discussion to do so) and adopts the Katello triage workflow, this would break that workflow as an FYI.

**Comment by ekohl** [comment]
> If Foreman core tries to do core triage (which there is a discussion to do so) and adopts the Katello triage workflow, this would break that workflow as an FYI.

How exactly would this be broken? Because the release will always be backlog rather than empty and I only change it if it's empty?

@ares looks like I incorrectly highlighted you

**Comment by ares** [comment]
I think hardcoding the next release id is not great. Can't we get the list and find the most recent one? That could then work for every plugin too. Otherwise I'm definitely up for testing, if we see problems, we can always revert.

**Comment by ehelms** [comment]
The way Katello triage works is `empty` release means `untriaged`. An issue is always set to the oldest release it's going-in in Redmine. So if empty is designed to allow a team to triage issues into the correct release auto flipping can result in missing issues (e.g. issue B needs to go into 1.17.3 but its assigned to 1.19.0 due to auto flipping instead of a human deciding).

**Comment by ekohl** [comment]
In that case I think we handle it mostly. Since we don't overwrite it, this will now work for untriaged issues. If we treat the backlog release as an empty release and set it to the next version, will this then work?

**Comment by GregSutcliffe** [comment]
We're now using a dedicated "Triaged" checkbox in core, so setting the fixed_verison_id isn't a terrible idea. 

@tbrisker as the release manager, would you like to see this in some form? Given the Forthcoming Way of Things, should this set Target Version, or Fixed-In field (or both)?

**Comment by ehelms** [comment]
@tbrisker This looks like its waiting on you

**Comment by tbrisker** [comment]
Oops, forgot about this. In core projects we now use the fixed-in version to indicate which version includes the fix.

**Comment by tbrisker** [comment]
@ohadlevy you asked about auto-setting the release yesterday, this is wip to do that

**Comment by ekohl** [comment]
I do intend to pick this up again at some point, but very likely in the Python version because that's much easier for me. It has a cleaner structure to catch a specific event (`pull_request/merged`).

**Comment by ekohl** [comment]
Replaced by https://github.com/theforeman/prprocessor/pull/131

**Pull request closed without merging**
