### PR TITLE
Skip commit style checks for WIP PRs

### PR DESCRIPTION
**Pull request by ekohl**
Closes GH-37

### CODE REVIEW

**Comment by ekohl** [comment]
Will send an email for foreman-dev about this.

**Comment by ekohl** [comment]
Text for when we roll out:

> tl;dr: Use [WIP] at the start of your PR subject to disable messages about incorrect commit messages
> 
> Longer version:
> 
> Many of us have Work In Progress PRs where we just append changes for review until we're happy - then we squash it all into neat commits. Until the squashing, theforeman-bot will spam like crazy. With
https://github.com/theforeman/prprocessor/pull/72 merged you can now prefix your PR with [WIP] to disable the message. It will fail the build but not post a message.

**Comment by lzap** [comment]
Thanks guys, we might want to change our PR template, not sure if we have any (I use hub CLI tool) but I think we had one.

**Comment by ekohl** [comment]
That's a good one. Users are more likely to read that than a one time announcement on foreman-dev.

**Comment by lzap** [comment]
Added https://github.com/theforeman/foreman/pull/5099 as my proposal.

**Pull request merged**
