### PR TITLE
Fixes #15: Assign assigned field of issue if user mapping is defined

### LINKED ISSUE #15: Set Redmine issue assignee to PR author
We should set the Redmine issue assignee field to the user account of the person who opened the pull request.

This might have to rely on a hardcoded lookup table, as Redmine [doesn't have a user search facility](http://www.redmine.org/issues/7484) unless you're an admin (and I'd rather not have those permissions given to this app), which we could have used to search by git or GitHub e-mail address.

### PR DESCRIPTION
**Pull request by ehelms**
The provided script will query github for all members of theforeman
and katello organizations and build a list of available users. This
list must be then mapped to the IDs from Redmine for that particular
user.

### CODE REVIEW

**Comment by ehelms** [comment]
I did not live test this as I would like to get input on the idea first -- I could try filling this out as part of this PR or merge this and then someone fill it in after the fact.

**Comment by domcleal** [comment]
Fine by me.  We may be able to search Redmine's database by name or email address to match up some user accounts (one-off), but I think that needs admin level access so that'd just be a way to populate the data.

**Comment by ehelms** [comment]
Tested this with success against Redmine for a single issue. I also added IDs for those I could easily see via the Katello members page. We could try automating the rest, combing through the Foreman members list.

**Comment by domcleal** [comment]
Thanks, it's merged and now live.  I'll fill in a few Foreman ones in a bit, and perhaps we could just e-mail to -dev once I've done that to invite people to add their own if they wish.

**Comment by ehelms** [comment]
:+1: My thoughts exactly (emailing -dev to fill in the rest) I can do that if you like -- just ping me when you've added what you want to add

**Comment by domcleal** [comment]
Done!  ce22256

**Pull request merged**
